#include "vertexBuffer.h"


namespace lyt {
	SHADER_TYPE_IMPL(Float);
	SHADER_TYPE_IMPL(Float2);
	SHADER_TYPE_IMPL(Float3);
	SHADER_TYPE_IMPL(Float4);
	SHADER_TYPE_IMPL(Int);
	SHADER_TYPE_IMPL(Int2);
	SHADER_TYPE_IMPL(Int3);
	SHADER_TYPE_IMPL(Int4);
	SHADER_TYPE_IMPL(Mat2);
	SHADER_TYPE_IMPL(Mat3);
	SHADER_TYPE_IMPL(Mat4);
	SHADER_TYPE_IMPL(Bool);
}
